gakumac/olivebodycare.healthcare

- nuxt.config.js
- pages/about/beginner.vue
- pages/about/contact.vue
- pages/about/greeting.vue
- pages/about/index.vue
- pages/about/qa.vue
- pages/about/staff.vue
- pages/menu/fertility-treatment.vue
- pages/menu/index.vue
- pages/menu/massage.vue
- pages/menu/pelvis-correction/diet.vue
- pages/menu/pelvis-correction/index.vue
- pages/menu/pelvis-correction/sango.vue
- pages/menu/seitai/index.vue
- pages/menu/seitai/option.vue
- pages/menu/seitai/sango.vue
- pages/menu/shinkyu/index.vue
- pages/menu/shinkyu/menstruation.vue
- pages/menu/shinkyu/option.vue
- pages/menu/traffic-accident.vue
- pages/reserve.vue
- pages/salon/aobadai.vue
- pages/salon/index.vue
- pages/salon/maruyamacho.vue
- pages/salon/tamaplaza.vue
- pages/voice.vue
resolve #11
- healthscare → healthcare に修正
> URLのスペルミスを修正

- pages/voice.vue
pagetitle title="患者様の声"
pagetitle h1="患者様の声"
に修正
> voice.vueの<pagetitle>部分をtilteからh1に修正

- pages/salon/index.vue
- pages/salon/maruyama.vue
・治療院一覧の札幌円山店の予約リンクを有効にする
・円山店詳細の電話番号を追加
> fix：前回の漏れを修正（札幌円山店の予約リンクを有効にする）

- components/index/Reason.vue
・説明文を一部変更
・写真、文字のBreakpointsをsm,lg,xlを追加して微調整。
> fix：トップページの選ばれる理由を修正

- nuxt.config.js
- package.json
- yarn.lock
https://ja.nuxtjs.org/faq/google-analytics/
こちらの公式ガイドに従い
https://github.com/nuxt-community/analytics-module
こちらのモジュールをインストール（yarn add @nuxtjs/google-analytics）
セットアップガイドに従いnuxt.config.jsに追記。
> add：グーグルアナリティクスを導入

- nuxt.config.js
- package.json
- yarn.lock
https://github.com/nuxt-community/sitemap-module
こちらのサイトを参考に
sitemap-moduleをインストール（yarn add @nuxtjs/sitemap）
ガイドに従い nuxt.config.jsに追記
http://localhost:3000/sitemap.xmlで確認済み
> add：sitemap-moduleを導入

- layouts/default.vue
- layouts/reserve.vue
- layouts/toppage.vue
> cannonicalタグの追加

- layouts/default.vue
- layouts/reserve.vue
- layouts/toppage.vue
先ほどのcannonicalタグの追加でエラーが出てしまった為
yarn lint --fixで修正（ , を削除）
> cannonicalタグの追加を修正

- components/index/Accesstop.vue
- components/index/Media.vue
- components/index/Menutop.vue
- components/index/Postscript.vue
- components/index/Problem.vue
- components/index/Qatop.vue
- components/index/Symptoms.vue
- components/index/Target.vue
- components/index/Voicetop.vue
・トップページ全体のbreakpointsを調整
・その他微調整
> トップページ全体のbreakpointsを調整

- components/salon/Maruyamainfo.vue
- components/salon/Maruyamavisit.vue
- pages/salon/maruyama.vue
・pages/salon/maruyamaの情報を一部componentsに移行
・待合室・駐車場情報を追加
> 丸山店の情報を一部componentsに移行、情報を追加

- components/salon/Maruyamavisit.vue
> 札幌丸山店の一部CSSを修正

- components/about/Contactform.vue
- components/footer/Stickyfooter.vue
- components/index/Accesstop.vue
- components/index/After.vue
- components/index/Postscript.vue
- components/index/Problem.vue
- components/index/Reason.vue
- components/reserve/ReserveSalon.vue
- pages/reserve.vue
・フッターの記述を一部変更
・各ページのデザインを一部変更
・トップページに申し込みフォームを追加。
・reserveページをcomponentsに分割
> トップページに申し込みフォームを追加

- components/index/Accesstop.vue
> トップページ丸山にキャンペーン告知を追加

- components/about/Contactform.vue
- pages/about/contact.vue
・メール予約・問い合わせのフッターの『24時間予約はこちら！』を消去
> メール予約のフッターを変更

- components/footer/Footer1.vue
- components/footer/Stickyfmaruyama.vue
- components/footer/Stickyfooter.vue
- components/index/After.vue
- components/index/Postscript.vue
- components/index/Problem.vue
- components/index/Reason.vue
- components/reserve/ReserveSalon.vue
- components/salon/maruyama/MaruyamaPs.vue
- components/salon/maruyama/Maruyamainfo.vue
- components/salon/maruyama/Maruyamamessage.vue
- components/salon/maruyama/Maruyamavisit.vue
- components/salon/maruyama/Maruyamavoice.vue
- pages/salon/index.vue
・予約ボタンのサイズを大きく（large）する
・電話ボタンにアイコンを追加
・フッターのサイズを調整
> 予約ボタンのサイズを大きくする

- components/footer/StickyfAobadai.vue
- components/footer/Stickyfmaruyama.vue
- components/footer/Stickyfooter.vue
- components/index/Accesstop.vue
- components/reserve/ReserveAobadai.vue
- components/reserve/ReserveMaruyama.vue
- components/reserve/ReserveSalon.vue
- components/salon/maruyama/MaruyamaPs.vue
- components/salon/maruyama/Maruyamainfo.vue
- components/salon/maruyama/Maruyamamessage.vue
- components/salon/maruyama/Maruyamavisit.vue
- components/salon/maruyama/Maruyamavoice.vue
- pages/salon/index.vue
> サイト内リンクの記述を変更

- components/footer/StickyfAobadai.vue
- components/footer/Stickyfmaruyama.vue
- components/footer/Stickyfooter.vue
- components/index/Accesstop.vue
- components/reserve/ReserveAobadai.vue
- components/reserve/ReserveMaruyama.vue
- components/reserve/ReserveSalon.vue
- components/salon/maruyama/MaruyamaPs.vue
- components/salon/maruyama/Maruyamainfo.vue
- components/salon/maruyama/Maruyamamessage.vue
- components/salon/maruyama/Maruyamavisit.vue
- components/salon/maruyama/Maruyamavoice.vue
- pages/salon/index.vue
Reverts gakumac/olivebodycare.healthcare#56
> Revert "サイト内リンクの記述を変更"

- components/footer/Stickyfmaruyama.vue
- pages/salon/index.vue
> ボタンの誤字、リンクを修正

- components/index/After.vue
- components/salon/aobadai/AobadaiAfter.vue
- components/salon/aobadai/AobadaiMessage.vue
- components/salon/aobadai/AobadaiVoice.vue
- pages/salon/aobadai.vue
・プロフィールを追加
・施術後メッセージを追加
・ホームの施術後メッセージを太字に変更
> 青葉台店に施術後メッセージを追加

- pages/reserve/tamaplaza.vue
> たまプラーザ予約ページパンくず修正

- components/index/Accesstop.vue
> アクセスマップのレイアウト崩れを修正

- components/campaign/MaruyamaCp.vue
> 円山店のキャンペーン変更

- components/campaign/MaruyamaCp.vue
> 円山店キャンペーン情報を変更

- assets/configs/menus.js
- components/about/MedicalQuestionnaire.vue
- pages/about/medical-questionnaire.vue
> 問診票記入ページを追加

- nuxt.config.js
> mdアイコンの指定方法を変更

- components/index/Header1.vue
- pages/news/info200305.vue
・pages/news/200305.vueを追加
・トップページのヘッダー下にコロナ対策ページへのリンクを追加
> コロナ対策ページの作成

- pages/news/info200305.vue
> コロナウイルス対応ページを修正

- pages/news/info200305.vue
> コロナ対策実施内容を追加

- components/about/MedicalQuestionnaire.vue
> 問診票ページに宮崎台店を追記

- components/salon/maruyama/Maruyamainfo.vue
- components/salon/maruyama/Maruyamamessage.vue
- components/salon/miyazakidai/MiyazakidaiInfo.vue
> youtube動画を追加

- components/NavMenus.vue
> リクルートページへのボタンを追加
